name: Publish Docker image to GHCR

# Triggers
on:
    workflow_dispatch:
        inputs:
            release_tag:
                description: "Release tag to build the Docker image from"
                required: true
                default: "1.0.0"

permissions:
    contents: read
    packages: write

jobs:
    build-and-push-bookworm:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push multi-platform image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./containers/prebuilt.bookworm.Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  build-args: |
                      GITHUB_RELEASE_VERSION=${{ github.event.inputs.release_tag }}
                  tags: |
                      ghcr.io/${{ github.repository }}:${{ github.event.inputs.release_tag }}
                      ghcr.io/${{ github.repository }}:${{ github.event.inputs.release_tag }}-bookworm-prebuilt
                      ghcr.io/${{ github.repository }}:${{ github.event.inputs.release_tag }}-bookworm
                      ghcr.io/${{ github.repository }}:latest-bookworm-prebuilt
                      ghcr.io/${{ github.repository }}:latest-bookworm
                      ghcr.io/${{ github.repository }}:latest

    build-and-push-alpine:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push multi-platform image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./containers/prebuilt.alpine.Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  build-args: |
                      GITHUB_RELEASE_VERSION=${{ github.event.inputs.release_tag }}
                  tags: |
                      ghcr.io/${{ github.repository }}:${{ github.event.inputs.release_tag }}-alpine-prebuilt
                      ghcr.io/${{ github.repository }}:${{ github.event.inputs.release_tag }}-alpine
                      ghcr.io/${{ github.repository }}:latest-alpine-prebuilt
                      ghcr.io/${{ github.repository }}:latest-alpine
